# Generated by Django 5.2.1 on 2025-06-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicvisit',
            old_name='date_of_visit',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='clinicvisit',
            name='complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
