# Generated by Django 5.2.1 on 2025-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_of_visit_clinicvisit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
