# Generated by Django 5.2.1 on 2025-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clinicvisit_first_name_clinicvisit_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='level',
            field=models.CharField(default='', max_length=255),
        ),
    ]
