# Generated by Django 5.2.1 on 2025-06-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clinicvisit_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicvisit',
            name='department',
        ),
        migrations.RemoveField(
            model_name='clinicvisit',
            name='level',
        ),
    ]
