# Generated by Django 5.2.1 on 2025-06-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_clinicvisit_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicvisit',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clinicvisit',
            name='last_name',
        ),
    ]
