# Generated by Django 5.2.1 on 2025-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_status_inventory_inventory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicvisit',
            old_name='complaints',
            new_name='complaint',
        ),
    ]
