# Generated by Django 5.2.1 on 2025-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_complaints_clinicvisit_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicvisit',
            name='complaint',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clinicvisit',
            name='medical_intervention',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clinicvisit',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
    ]
