# Generated by Django 5.2.1 on 2025-06-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inventory_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
