# Generated by Django 5.2.1 on 2025-06-12 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_inventory_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='last_name',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies_foods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='asthma_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='atopic_dermatitis_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='carries_inhaler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diabetes_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='epilepsy_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='eye_vision_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='eye_vision_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fathers_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fathers_home_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fathers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hearing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hearing_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='heart_disorder_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hospitalization_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='impetigo_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='meningitis_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mothers_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mothers_home_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mothers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='other_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='other_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pneumonia_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='psoriasis_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='scoliosis_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='severe_allergic_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tuberculosis_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='urinary_disorder_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitiligo_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='wears_eyeglasses_or_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
