# Generated by Django 5.2.1 on 2025-06-12 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_medicalrecord_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
