# Generated by Django 5.2.1 on 2025-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_medicalrecord_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='residence',
            field=models.CharField(choices=[('both', 'Both Parents'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], default='both', max_length=100),
        ),
    ]
