# Generated by Django 5.2.1 on 2025-06-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_medicalrecord_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='allergies_foods',
            new_name='food_allergies',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='allergies_medications',
            new_name='medication_allergies',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='primary_contact_name',
            new_name='primarycontact_name',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='primary_contact_number',
            new_name='primarycontact_number',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='severe_allergic_reaction',
            new_name='severeallergic_reaction',
        ),
    ]
