# Generated by Django 5.2.1 on 2025-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_allergies_foods_medicalrecord_food_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='age',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
