# Generated by Django 5.2.1 on 2025-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_medicalrecord_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='atopic_dermatitis_age',
            new_name='illness_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diabetes_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='epilepsy_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='heart_disorder_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='impetigo_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='meningitis_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='other_conditions',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='pneumonia_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='psoriasis_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='scoliosis_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='tuberculosis_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='urinary_disorder_age',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='vitiligo_age',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='illness',
            field=models.CharField(choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('meningitis', 'Meningitis'), ('tuberculosis', 'Tuberculosis'), ('pneumonia', 'Pneumonia'), ('heart_disorder', 'Heart Disorder'), ('urinary_disorder', 'Urinary Disorder'), ('epilepsy', 'Epilepsy'), ('scoliosis', 'Scoliosis'), ('psoriasis', 'Psoriasis'), ('vitiligo', 'Vitiligo'), ('atopic_dermatitis', 'Atopic Dermatitis'), ('impetigo', 'Impetigo')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='other_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='eye_vision_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hearing_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospitalization_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
