# Generated by Django 5.2.1 on 2025-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_atopic_dermatitis_age_medicalrecord_illness_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='illness',
            field=models.CharField(choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('meningitis', 'Meningitis'), ('tuberculosis', 'Tuberculosis'), ('pneumonia', 'Pneumonia'), ('heart_disorder', 'Heart Disorder'), ('urinary_disorder', 'Urinary Disorder'), ('epilepsy', 'Epilepsy'), ('scoliosis', 'Scoliosis'), ('psoriasis', 'Psoriasis'), ('vitiligo', 'Vitiligo'), ('atopic_dermatitis', 'Atopic Dermatitis'), ('impetigo', 'Impetigo'), ('other_illness', 'Other Illness')], default='none', max_length=100),
        ),
    ]
