# Generated by Django 5.2.1 on 2025-11-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_medicalrecord_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='medical_record_signatures/'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='asthma_history',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='carries_inhaler',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='eye_vision_problem',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hearing_problems',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='severeallergic_reaction',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='wears_eyeglasses_or_contacts',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
