# Generated by Django 5.2.1 on 2025-11-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_medicalrecord_signature_medicalrecord_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='verification',
            field=models.CharField(blank=True, choices=[('yes', 'Yes')], max_length=3, null=True),
        ),
    ]
