# Generated by Django 5.2.1 on 2025-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_medicalrecord_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='verification',
            field=models.CharField(blank=True, choices=[('yes', 'Yes')], max_length=3, null=True),
        ),
    ]
