# Generated by Django 5.2.1 on 2025-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_medicalrecord_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='permission',
            field=models.CharField(blank=True, choices=[('yes', 'Yes')], max_length=3, null=True),
        ),
    ]
