# Generated by Django 5.2.1 on 2025-11-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_medicalrecord_exception_medicalrecord_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='permission',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
