# Generated by Django 5.2.1 on 2025-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
