# Generated by Django 5.2.1 on 2025-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_age_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default=''),
        ),
    ]
