# Generated by Django 5.2.1 on 2025-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_department_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
