# Generated by Django 5.2.1 on 2025-06-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
