# Generated by Django 5.2.1 on 2025-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
