# Generated by Django 5.2.1 on 2025-06-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_department_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
