# Generated by Django 5.2.1 on 2025-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('BED', 'Basic Education Department'), ('BSN', 'Bachelor of Science in Nursing'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSBA', 'Bachelor of Science in Business Administration Major in Operational Management'), ('BSP', 'Bachelor of Science in Psychology'), ('BSRT', 'Bachelor of Science in Radiologic Technology'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BEEd', 'Bachelor of Science in Elementary Education'), ('BSEd-Filipino', 'Bachelor of Science in Secondary Education Major in Filipino'), ('BSEd-English', 'Bachelor of Science in Secondary Education Major in English'), ('College', 'College Department'), ('Accounting', 'Accounting Department')], max_length=100),
        ),
    ]
