# Generated by Django 5.2.1 on 2025-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('first_year', '1st Year'), ('second_year', '2nd Year'), ('third_year', '3rd Year'), ('fourth_year', '4th Year')], max_length=100),
        ),
    ]
