# Generated by Django 5.2.1 on 2025-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('BED', 'Basic Education Department'), ('BSN', 'Bachelor of Science in Nursing'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSBA', 'Bachelor of Science in Business Administration Major in Operational Management'), ('BSP', 'Bachelor of Science in Psychology'), ('BSRT', 'Bachelor of Science in Radiologic Technology'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BEEd', 'Bachelor of Science in Elementary Education'), ('BSEd-Filipino', 'Bachelor of Science in Secondary Education Major in Filipino'), ('BSEd-English', 'Bachelor of Science in Secondary Education Major in English'), ('College', 'College Department'), ('Accounting', 'Accounting Department'), ('Office', 'Office of the President and CEO, COO'), ('Compliance', 'Accounting Department'), ('HumanResource', 'Accounting Department'), ('HealthServices', 'Accounting Department'), ('ICT', 'Accounting Department'), ('Guidance', 'Accounting Department'), ('Marketing', 'Accounting Department'), ('Procurement', 'Accounting Department'), ('Housekeeping', 'Accounting Department'), ('Security', 'Accounting Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('first_year', '1st Year'), ('second_year', '2nd Year'), ('third_year', '3rd Year'), ('fourth_year', '4th Year')], max_length=100),
        ),
    ]
